apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-init
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
stringData:
  MOSQUITTO_USERNAME: "{{ .Values.config.mosquitto.username }}"
  MOSQUITTO_PASSWORD: "{{ .Values.config.mosquitto.password }}"
  