apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-lb
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }}
